### PR TITLE
Setup handbook

### PR DESCRIPTION
**Pull request by avassem85**
- [x] Setup basic handbook
- [ ] Move Mutation Testing
- [ ] Move FAQ
- [x] Move Mutator Types

**Move documentation from website / github**

_Stryker_
- [ ] Getting Started
- [x] Guides (Angular & React)
- [x] Technical Reference
- [ ] Update navigation on [wiki](https://github.com/stryker-mutator/stryker/wiki)

 _Stryker4s_
- [ ] Getting Started
- [ ] Update navigation on [wiki](https://github.com/stryker-mutator/stryker4s/wiki)

 _Stryker.NET_
- [ ] Getting Started
- [ ] Update navigation on [wiki](https://github.com/stryker-mutator/stryker-net/wiki)

### CODE REVIEW

**Comment by legopiraat** [comment]
Initial getting started for stryker4s is available in merge request #5

**Comment by simondel** [comment]
I'm fine with not having the _Moved_ pages. If people get a 404, they should still be able to find the configs from the root of the repo.

We should also update #4 with the new path.

**Comment by nicojs** [comment]
@simondel 

> I'm fine with not having the Moved pages.

I'm not fine. See this error page:

image

That's not helpful for newcomers. 

Instead, @avassem85 did a great job with this: 

image

Much better, right?

**Comment by simondel** [comment]
@nicojs How long would you like to keep those pages? Because you will also have users that click through the handbook, find the moved page and then go to the correct page.

**Comment by nicojs** [comment]
A month or so would be good enough. We uodate all links to the page right away, but cannot do that before it is merged. Too bad we cannot do a 301 redirect :(

**Comment by simondel** [comment]
Fine by me, let's remove it in Oktober 👍

**Comment by nicojs** [comment]
@avassem85 can we merge this ASAP? It is a bit blocking: https://github.com/stryker-mutator/stryker/issues/1124

**Pull request merged**
