### PR TITLE
Typo fix: "a" in scala getting started

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
I promise this isn't _just_ for Hacktoberfest 😂

### CODE REVIEW

**Comment by simondel** [comment]
Thanks mate :) By the way, do MS employees also get the MS t-shirt when they contribute this month? 🤔 I still have to look for a nice issue to pick up.

**Comment by hugo-vrijswijk** [comment]
@simondel I believe anyone can get a special t-shirt if they contribute to any MS repo. [See here](https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/?WT.mc_id=hacktoberfest-none-beverst)

**Comment by JoshuaKGoldberg** [comment]
> do MS employees also get the MS t-shirt

Alas, we don't 😢 ([link](https://twitter.com/BerndVerst/status/1042106017318760450)) I'll have to make do with finding time to contribute to Stryker instead! ✨

**Comment by nicojs** [comment]
We can send you some socks 
image

**Comment by JoshuaKGoldberg** [comment]
Socks make everything better!

...but first I'd like to earn them. Will send you a few PRs!

**Pull request merged**
